CREATE DATABASE XRAY;

USE XRAY;

CREATE TABLE USUARIO (
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    NOME VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE USUARIO_HISTORICO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INTEGER NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

DELIMITER //

CREATE TRIGGER HISTORICO_USUARIO
AFTER UPDATE ON USUARIO
FOR EACH ROW
BEGIN
    INSERT INTO USUARIO_HISTORICO (USUARIO_ID, CPF, NOME, SENHA, DATA_ATUALIZACAO)
    VALUES (NEW.ID, NEW.CPF, NEW.NOME, NEW.SENHA, NOW());
END //

DELIMITER ;


CREATE TABLE CALCULO_LOG(
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INTEGER REFERENCES USUARIO(ID_USUARIO),
    REGIAO VARCHAR(255),
    PROJECAO VARCHAR(255),
    ESPESSURA INTEGER,
    RENDIMENTO INTEGER,
    BSF INTEGER,
    KV INTEGER,
    MS INTEGER,
    MA INTEGER,
    RESULTADO DECIMAL(15,2)
);

CREATE VIEW CALCULOS AS
SELECT
	C.REGIAO,
    C.PROJECAO,
    C.ESPESSURA,
    C.RENDIMENTO,
    C.BSF,
    C.KV,
    C.MS,
    C.MA,
    C.RESULTADO,
    U.NOME AS USUARIO
FROM CALCULO_LOG C
JOIN USUARIO U ON U.ID = C.ID_USUARIO;

SELECT * FROM CALCULOS;
